### ISSUE TITLE
vector Jan 2020 RC 

### ISSUE THREAD

**Issue by cartazio** [haskell/vector#266]
@gwils @boarders @fumieval @RyanGlScott  @chessai  @hvr  @andrewthad 
i'm thinking https://travis-ci.org/haskell/vector/builds/633862783 (current master) should work as a minor release bump on the 0.12 series, or a reasonably stable 0.13 series, 

please provide feedback on if thers any outstanding tickets or PRS you'd like me to make sure to include (ideally with GH flavored markdown checkboxes for the things you want so i can keep track and get it over with today :) )

**Comment by andrewthad** [comment]
These are both pretty straightforward PRs that I would like to see merged:

- [_] https://github.com/haskell/vector/pull/209 (`fromArray`)
- [_] https://github.com/haskell/vector/pull/226 (monadic map maybe)

**Comment by fumieval** [comment]
As long as Y or Z in version `X.Y.Z` is bumped, I'm fine either way.

**Comment by cartazio** [comment]
Atm I think the changes in master reflect a minor bump aside from perhaps
the roles annotation for storable.

**Comment by cartazio** [comment]
@hvr and Ryan: care to way in on pvp Rec ?

**Comment by sjakobi** [comment]
It would be nice if this optimization could be included, but it shouldn't block a release:

* [ ] #261: Optimize `eq[By]` and `Eq` instances by comparing sizes first

**Comment by lehins** [comment]
Per [request](https://github.com/haskell/vector/issues/264#issuecomment-573164407) from @cartazio: issues related to current RC that need to been addressed:
* [ ] #255 - prior to making a new release a git tag for current v0.12.0.3 needs to be created (that actually matches the released version)
* [ ] #256 - make sure new release builds with latest version of `primitive`
* [ ] #258 - ensure #168 is added to new release
* [ ] #264 - ensure #194 is added to new release

**Comment by cartazio** [comment]
@lehins I think master should build now with primitive 0.7 :), i cherry picked the commit needed

**Comment by cartazio** [comment]
also i think that v0.12.0.3 is live

**Comment by cartazio** [comment]
i'm going to wait a few days to do anything more intricate till after i'm done with my fever,

**Comment by enobayram** [comment]
Per [request](https://github.com/haskell/vector/pull/231#issuecomment-574738926) from @cartazio: It seems like people are occasionally getting bitten by the cryptic boxed `Vector` + compaction issue (#220), spending a lot of time debugging (I'm one of the victims). This PR adds a hint to the ensuing error message:
   - [ ] Ensure #231 is added to the new release

**Comment by cartazio** [comment]
https://github.com/haskell/vector/issues/268 is gonna take priority! :)

**Comment by cartazio** [comment]
i'm probably gonna have to backport the fix to previous minor/major versions too

**Comment by cartazio** [comment]
- [ ] #188 
and 
- [ ] #257
and 
- [ ] #268 

probably also should figure out how to use #229 and also make sure current master is green on full build matrix of ghc versions at O2/O1

**Comment by RyanGlScott** [comment]
I'd like to see commit 4b1ba83524b967d561e076a22578b20afc1ef3e7 (which bumps the upper version bounds on `ghc-prim` to `<0.7`) on Hackage soon, given that GHC 8.10.1-rc1 is out. I'm not picky about whether this is done via a Hackage revision or a new release.

**Comment by cartazio** [comment]
Let’s do both!

I got derailed by the investigating how to best improve vector ci because
of the rules bug.  Back on track. I’ll do a relaxation for 0.12.0.3 though
if another trustee beats me to it plz let me know :)

**Comment by cartazio** [comment]
@RyanGlScott can 0.12.0.3 have its bounds relaxed safely?

**Comment by RyanGlScott** [comment]
@cartazio, indeed. I've verified that `vector-0.12.0.3` builds without issue using `base-4.14.0.0` and `ghc-prim-0.6.1`.

**Comment by cartazio** [comment]
ok, action items left (condensed)

- [ ] #209 (fromArray)
    - [ ] has tests
- [ ]  #226 (monadic map maybe)
  - [ ] has tests
both of these lack even a unit test, and given how pernicious and tricky vector bugs have been historically , i'm loath to merge sans test (and my brain is too fried this week to feel confident about juggling that among my other hackery)

on the current bugs side of things around slices and overflow bugs we have 

- [ ] #188
and
- [ ]#257

and the question of whats a good for the next release vs whats a good long term choice in semantics

**Comment by lehins** [comment]
I'll get a fix with a test case submitted for #257 later on tonight.

**Comment by cartazio** [comment]
also 

- [ ] possibly revert the roles patch unless folks think the roles change in question isn't a mjor version bump (cc @ekmett @RyanGlScott ). i'm not sure ?
- [ ] At the very least, i'm not sure if the Vector Primitive Roles are correct unless take the primitive maintainer hat on and say "users REALLY should never write their own instances that aren't a new type of a provided one"

**Comment by RyanGlScott** [comment]
The changes in #235 arguably deserve a major version bump, since there is code that one could write today that will no longer typecheck after applying those changes. I'd certainly be OK with reverting it if it would make the next release process smoother.

**Comment by cartazio** [comment]
@RyanGlScott  also i'm pretty sure the predecessor patch by dominic was wrong too,  but i'm not sure

**Comment by cartazio** [comment]
also 

- [ ]  make sure changelog reflects everything

**Comment by cartazio** [comment]
ok that leaves #188 (and the main question i have is whether the commit language as it is currently is wrong and does it handle both )

plus tests to gate inclusion of mapconcatmaybe+fromlist

**Comment by lehins** [comment]
Might as well add to this list:
* [ ] #285 / #282

**Comment by cartazio** [comment]
yay! (i'm gonna wind down for the rest of the day before circling back on this stuff)

also thinking maybe the changelog notes should (ideally?! mention ticket # and or pr # when applicable, or commit id? idk. any improvment is an improvement)

**Comment by lehins** [comment]
Ideally I think we could also switch changelog to changelog.md and add links to issues, not just their #

**Comment by cartazio** [comment]
Yes! Good idea.

**Comment by cartazio** [comment]
@lehins i changed the `changelog` to `changelog.md` so we can make it pretty

**Comment by cartazio** [comment]
ok, action items left afaik (if we hew to this being a minor version bump)

- [ ] (after making a 0.12.1.X branch) revert the roles annotations (i think some of the roles are annotated wrong atm)

if we want fromArray and mapMaybe
- [ ] merge them into a branch, add tests, apply to master

irrespective of which path in the choose our adventure
-  [ ] make sure changelog is correct

**Comment by Shimuuar** [comment]
Since we're planning to do a release I decided to go thorough master branch and check how many change that require major version bump it contains. It turns out: a lot, really lot. More than half probably if we discount documentation fixes and fiddling with travis. Mostly it's about adding more instances:

### Require major bump

- PR #180 Make maximumBy same as list version
- PR #160 make Mutable injective
- PR #185 Add Unbox for Identity & Const
- PR #194 Add Unbox for everything in base
- PR #205 Add Data instances for immutable vectors
- PR #224 Add role annotations
- PR #235 Make Storable nominally roled
- PR #233 Add NFData1 for vector types
- 8612af0f5eec29dcea78e3a40f215ec0867cb341 Adapt for MonadFail instances (?)

### Don't require major bump
- PR #168 solve division by zero in storable
- PR #176 add partitionWith
- All last changes are bug fixes

All in all it looks like easiest option is to just make 0.13.0.0 release. With almost three years worth of changes it almost inevitable. And if we do want to release 0.12.1 it would be easier to cherry pick bug fixes to `v0.12` branch

**Comment by cartazio** [comment]
Adding new type class instances is a minor version bump per PVP https://pvp.haskell.org/
(so adding storable/monadfail/unbox/nfdata* instances are minor bumps)

maximumBy change would be  major bump

Role changes (some of which are wrong atm, i suspect that everything but Boxed vectors needs nominal roles, but I need to think about what the vector internal contract on those classes is atm!) would def be a major bump

as for injective type families, in hindsight, perhaps a minor change, though they are in the `0.12.0.X`, for `x>= 2` releases. At the time my reasoning (perhaps correctly, perhaps  not) was that making it injective would only improve type inference.  One package did break, to my dismay (though their pure and mutable instances conflated the Mutable state token and a common reified "rts context" handle token that was shared in both settings. Though its now fixed)

by this path dependent history, and that the preceding releases having the injective type families,
I think as long as i revert the current roles and the maxby pieces, this can be a minor bump.

**Comment by cartazio** [comment]
to be clear: this reasoning is history/path-dependent and not what normal versioning should be based upon! :)

**Comment by cartazio** [comment]
"aka, because its in the previous family of releases, that inclusion does not trigger a major bump relative to the previous release"

**Comment by Shimuuar** [comment]
Problem with reverting breaking changes is it could be difficult to find all breaking changes. Roles for example were changed more than one time. I could have missed something. We have almost 3 years of patches and no one remember everything. Major bump is more conservative in that sense if release do break stuff well that was major bump.  We could backport bugfixes to v0.12 brang and made 0.12.04 release which at least fixes worst stuff

WRT roles. Unboxed clearly should be nominal since newtype can have completely different data instance when compared to underlying type. And I think same arguments could be made for primittive as for storable.

**Comment by cartazio** [comment]
i understand and agree with your worries, 
my approach for the roles code would be `shift command f "role"` on the project, rather than by hand cleanup reverting the two roles patches

**Comment by lehins** [comment]
@Shimuuar I think you mean backport bugfixes to v0.12 branch and make a **0.12.1** release, right?
> We could backport bugfixes to v0.12 brang and made 0.12.04 release

**Comment by cartazio** [comment]
the only breaking changes (relative to 0.12.0.2/3) we'd need to pull out for a `0.12.1.X` release would be Roles and the MaximiumBy right?

**Comment by cartazio** [comment]
to be clear: no current release of vector has roles annotations, so the revert there is simply to delete them in that branch

**Comment by cartazio** [comment]
wip/release/v0.12.1.X branch has the tentative release candidate, its available as a hackage candidate https://hackage.haskell.org/package/vector-0.12.1.0/candidate

please test that the codes you like work with it :)

**Comment by cartazio** [comment]
https://github.com/haskell/vector/tree/wip/release/v0.12.1.X

**Comment by cartazio** [comment]
https://travis-ci.org/haskell/vector/builds/644632295

**Comment by cartazio** [comment]
```shell
cabal install https://hackage.haskell.org/package/vector-0.12.1.0/candidate/vector-0.12.1.0.tar.gz #  :) 
```
cc anyone who wants to check things work with it

**Comment by cartazio** [comment]
huh, that trick only works with cabal v1-install :(

**Comment by cartazio** [comment]
fuck, forgot to double check CI

**Comment by cartazio** [comment]
(though i guess tests not being buildable isn't the worst, will do a .1 bug fix and marking the .0 release unbuldable via adding a <0 constraint to base)

**Comment by cartazio** [comment]
taged, bagged, shipped!

https://hackage.haskell.org/package/vector-0.12.1.1

**Comment by cartazio** [comment]
theres a few good things that we didni't include, but the next release will be the 0.13 family and we can get that ready with some good baking over the next few weeks/months/quarter

**Comment by Shimuuar** [comment]
Time zones strike again. Couldn't andwer while sleeping.  I'm not sure that
I didn't miss anything important so I hope we didn't break anything of
importance in this release.

**Comment by cartazio** [comment]
Heh. All good. I’ve not heard any screaming yet and I did make sure a bunch
of things built locally.  ;)

Merry weekend. And again thanks for helping this release as good as it
likely is :)

**Comment by lehins** [comment]
@cartazio Thank you for getting this release done! Great work! And thanks to all those that have helped!
